Repository Pop-py/poppy-server, pull requests merged in 2024-11, with the labels that each got.

#9 [Feat]: 네이버 로그인 구현
  build.gradle
  src/main/java/com/poppy/common/auth/JwtTokenizer.java
  src/main/java/com/poppy/common/auth/cache/OAuthOTUCache.java
  src/main/java/com/poppy/common/auth/controller/OAuth2Controller.java
  src/main/java/com/poppy/common/auth/controller/TestUserController.java
  src/main/java/com/poppy/common/auth/dto/TokenRspDto.java
  src/main/java/com/poppy/common/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/poppy/common/auth/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/poppy/common/auth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/poppy/common/config/SecurityConfig.java
  src/main/java/com/poppy/common/config/SwaggerConfig.java
  src/main/java/com/poppy/common/config/security/SecurityConfig.java
  src/main/java/com/poppy/common/config/swagger/SwaggerConfig.java
  src/main/java/com/poppy/common/entity/BaseTimeEntity.java
  src/main/java/com/poppy/common/exception/BusinessException.java
  src/main/java/com/poppy/common/exception/ErrorCode.java
  src/main/java/com/poppy/common/util/ErrorResponder.java
  src/main/java/com/poppy/domain/user/entity/User.java
  src/main/java/com/poppy/domain/user/repository/UserRepository.java
  src/main/java/com/poppy/domain/user/service/UserService.java
Labels: 🔧 기능 구현

#10 [Feat]: 팝업스토어 정보 조회
  .gitignore
  build.gradle
  src/main/java/com/poppy/common/config/querydsl/QuerydslConfig.java
  src/main/java/com/poppy/common/config/security/SecurityConfig.java
  src/main/java/com/poppy/common/entity/BaseTimeEntity.java
  src/main/java/com/poppy/common/exception/ErrorCode.java
  src/main/java/com/poppy/domain/popupStore/controller/PopupStoreController.java
  src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreResponseDto.java
  src/main/java/com/poppy/domain/popupStore/entity/PopupStore.java
  src/main/java/com/poppy/domain/popupStore/repository/PopupStoreRepository.java
  src/main/java/com/poppy/domain/popupStore/repository/PopupStoreRepositoryCustom.java
  src/main/java/com/poppy/domain/popupStore/repository/PopupStoreRepositoryImpl.java
  src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java
  src/main/java/com/poppy/domain/storeCategory/entity/StoreCategory.java
Labels: 🔧 기능 구현

#11 [Fix]: 로그인 시 이메일 확인
  src/main/java/com/poppy/common/config/security/SecurityConfig.java
  src/main/java/com/poppy/domain/user/entity/User.java
  src/main/java/com/poppy/domain/user/service/UserService.java
Labels: 🐞버그 수정

#12 [Fix]: controller url 수정
  src/main/java/com/poppy/domain/popupStore/controller/PopupStoreController.java
Labels: 🐞버그 수정

#13 [Fix]: 로그인 시 네이버 정보를 바탕으로 업데이트
  src/main/java/com/poppy/domain/user/entity/User.java
  src/main/java/com/poppy/domain/user/service/UserService.java
Labels: 🐞버그 수정

#14 [Refactor]: 날짜 범위 검색 예외 처리 추가
  src/main/java/com/poppy/common/exception/ErrorCode.java
  src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java
Labels: ⚒️ 리팩토링

#16 [Refactor]: 토큰 및 인증 코드 Redis에 저장
  build.gradle
  src/main/java/com/poppy/common/auth/JwtTokenizer.java
  src/main/java/com/poppy/common/auth/cache/OAuthOTUCache.java
  src/main/java/com/poppy/common/auth/controller/OAuth2Controller.java
  src/main/java/com/poppy/common/auth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/poppy/common/config/redis/RedisConfig.java
  src/main/java/com/poppy/common/config/security/SecurityConfig.java
Labels: 🔧 기능 구현, ⚒️ 리팩토링

#17 [Feat]: 어플을 통한 예약 구현
  build.gradle
  src/main/java/com/poppy/PoppyApplication.java
  src/main/java/com/poppy/common/config/redis/RedisConfig.java
  src/main/java/com/poppy/common/config/security/SecurityConfig.java
  src/main/java/com/poppy/common/entity/BaseTimeEntity.java
  src/main/java/com/poppy/common/entity/Images.java
  src/main/java/com/poppy/common/entity/Token.java
  src/main/java/com/poppy/common/exception/ErrorCode.java
  src/main/java/com/poppy/common/exception/dto/ErrorRspDto.java
  src/main/java/com/poppy/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/poppy/common/util/ErrorResponder.java
  src/main/java/com/poppy/common/util/RedisInitializer.java
  src/main/java/com/poppy/domain/instagramReview/entity/InstagramReview.java
  src/main/java/com/poppy/domain/likes/entity/Likes.java
  src/main/java/com/poppy/domain/notification/entity/Notification.java
  src/main/java/com/poppy/domain/payment/entity/Payment.java
  src/main/java/com/poppy/domain/popupStore/controller/PopupStoreController.java
  src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreCalenderRspDto.java
  src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreResponseDto.java
  src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java
  src/main/java/com/poppy/domain/popupStore/dto/response/ReservationAvailableSlotRspDto.java
  src/main/java/com/poppy/domain/popupStore/entity/PopupStore.java
  src/main/java/com/poppy/domain/popupStore/repository/PopupStoreRepository.java
  src/main/java/com/poppy/domain/popupStore/repository/PopupStoreRepositoryImpl.java
  src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java
  src/main/java/com/poppy/domain/reservation/controller/ReservationController.java
  src/main/java/com/poppy/domain/reservation/controller/TestController.java
  src/main/java/com/poppy/domain/reservation/dto/ReservationReqDto.java
  src/main/java/com/poppy/domain/reservation/dto/ReservationRspDto.java
  src/main/java/com/poppy/domain/reservation/entity/PopupStoreStatus.java
  src/main/java/com/poppy/domain/reservation/entity/Reservation.java
  src/main/java/com/poppy/domain/reservation/entity/ReservationAvailableSlot.java
  src/main/java/com/poppy/domain/reservation/repository/ReservationAvailableSlotCustomRepository.java
  src/main/java/com/poppy/domain/reservation/repository/ReservationAvailableSlotCustomRepositoryImpl.java
  src/main/java/com/poppy/domain/reservation/repository/ReservationAvailableSlotRepository.java
  src/main/java/com/poppy/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/poppy/domain/reservation/service/RedisSlotService.java
  src/main/java/com/poppy/domain/reservation/service/ReservationService.java
  src/main/java/com/poppy/domain/review/entity/Review.java
  src/main/java/com/poppy/domain/user/entity/User.java
  src/main/java/com/poppy/domain/user/service/UserService.java
  src/test/java/com/poppy/domain/reservation/service/ReservationServiceTest.java
Labels: 🐞버그 수정, 💯 테스트, 🔧 기능 구현

#18 [Refactor]: 예약 관련 유효성, 예외 처리 추가
  src/main/java/com/poppy/common/exception/ErrorCode.java
  src/main/java/com/poppy/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/poppy/domain/popupStore/controller/PopupStoreController.java
  src/main/java/com/poppy/domain/reservation/controller/ReservationController.java
  src/main/java/com/poppy/domain/reservation/dto/ReservationReqDto.java
  src/main/java/com/poppy/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/poppy/domain/reservation/service/ReservationService.java
Labels: ⚒️ 리팩토링

#19 [Feat]: 예약 조회 및 삭제 구현
  src/main/java/com/poppy/common/exception/ErrorCode.java
  src/main/java/com/poppy/domain/popupStore/entity/PopupStore.java
  src/main/java/com/poppy/domain/popupStore/entity/ReservationType.java
  src/main/java/com/poppy/domain/reservation/controller/ReservationController.java
  src/main/java/com/poppy/domain/reservation/dto/ReservationReqDto.java
  src/main/java/com/poppy/domain/reservation/dto/ReservationRspDto.java
  src/main/java/com/poppy/domain/reservation/entity/Reservation.java
  src/main/java/com/poppy/domain/reservation/entity/ReservationAvailableSlot.java
  src/main/java/com/poppy/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/poppy/domain/reservation/service/RedisSlotService.java
  src/main/java/com/poppy/domain/reservation/service/ReservationService.java
  src/main/java/com/poppy/domain/user/controller/UserController.java
  src/main/java/com/poppy/domain/user/dto/UserReservationRspDto.java
  src/main/java/com/poppy/domain/user/entity/User.java
  src/main/java/com/poppy/domain/user/repository/LoginUserProvider.java
  src/main/java/com/poppy/domain/user/repository/LoginUserProviderImpl.java
  src/main/java/com/poppy/domain/user/service/UserService.java
  src/test/java/com/poppy/domain/reservation/service/ReservationServiceTest.java
Labels: 💯 테스트, 🔧 기능 구현

#21 [Feat]: 관리자 팝업스토어 등록 및 삭제 구현
  src/main/java/com/poppy/admin/controller/AdminController.java
  src/main/java/com/poppy/admin/service/AdminService.java
  src/main/java/com/poppy/common/config/security/SecurityConfig.java
  src/main/java/com/poppy/common/exception/ErrorCode.java
  src/main/java/com/poppy/domain/popupStore/dto/request/PopupStoreReqDto.java
  src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java
  src/main/java/com/poppy/domain/popupStore/entity/PopupStore.java
  src/main/java/com/poppy/domain/storeCategory/repository/StoreCategoryRepository.java
  src/main/java/com/poppy/domain/user/entity/Role.java
  src/main/java/com/poppy/domain/user/entity/User.java
Labels: 🔧 기능 구현

#22 [Fix]: 팝업 스토어 등록 시 슬롯 분배 수정
  src/main/java/com/poppy/admin/controller/AdminController.java
  src/main/java/com/poppy/admin/service/AdminService.java
  src/main/java/com/poppy/common/exception/ErrorCode.java
  src/main/java/com/poppy/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/poppy/domain/popupStore/dto/request/PopupStoreReqDto.java
  src/main/java/com/poppy/domain/popupStore/entity/PopupStore.java
  src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java
  src/main/java/com/poppy/domain/reservation/repository/ReservationAvailableSlotCustomRepository.java
  src/main/java/com/poppy/domain/reservation/repository/ReservationAvailableSlotCustomRepositoryImpl.java
  src/main/java/com/poppy/domain/user/entity/User.java
Labels: 🐞버그 수정, ⚒️ 리팩토링
