Repository Pop-py/poppy-server, pull requests merged in 2024-12, with the labels that each got.

#26 [Feat]: 리뷰 기능 및 좋아요
  src/main/java/com/poppy/common/exception/ErrorCode.java
  src/main/java/com/poppy/domain/likes/entity/ReviewLike.java
  src/main/java/com/poppy/domain/likes/repository/ReviewLikeRepository.java
  src/main/java/com/poppy/domain/review/controller/ReviewController.java
  src/main/java/com/poppy/domain/review/dto/request/ReviewReqDto.java
  src/main/java/com/poppy/domain/review/dto/response/ReviewLikeRspDto.java
  src/main/java/com/poppy/domain/review/dto/response/ReviewRspDto.java
  src/main/java/com/poppy/domain/review/entity/Review.java
  src/main/java/com/poppy/domain/review/repository/ReviewRepository.java
  src/main/java/com/poppy/domain/review/service/ReviewService.java
  src/main/java/com/poppy/domain/user/entity/User.java
  src/test/java/com/poppy/domain/review/service/ReviewServiceTest.java
Labels: 🔧 기능 구현

#28 [Feat]: 리뷰 sort type 별 조회
  src/main/java/com/poppy/domain/review/ReviewSortType.java
  src/main/java/com/poppy/domain/review/controller/ReviewController.java
  src/main/java/com/poppy/domain/review/repository/ReviewRepository.java
  src/main/java/com/poppy/domain/review/service/ReviewService.java
  src/test/java/com/poppy/domain/review/service/ReviewServiceTest.java
Labels: 🔧 기능 구현

#29 [Feat]: 결제 로직 구현
  src/main/java/com/poppy/admin/service/AdminService.java
  src/main/java/com/poppy/common/config/security/SecurityConfig.java
  src/main/java/com/poppy/common/exception/ErrorCode.java
  src/main/java/com/poppy/domain/payment/controller/PaymentController.java
  src/main/java/com/poppy/domain/payment/dto/ReservationPaymentRspDto.java
  src/main/java/com/poppy/domain/payment/entity/Payment.java
  src/main/java/com/poppy/domain/payment/entity/PaymentStatus.java
  src/main/java/com/poppy/domain/payment/repository/PaymentRepository.java
  src/main/java/com/poppy/domain/payment/service/PaymentService.java
  src/main/java/com/poppy/domain/payment/service/TossPaymentClient.java
  src/main/java/com/poppy/domain/popupStore/dto/request/PopupStoreReqDto.java
  src/main/java/com/poppy/domain/popupStore/entity/PopupStore.java
  src/main/java/com/poppy/domain/reservation/controller/ReservationController.java
  src/main/java/com/poppy/domain/reservation/controller/TestController.java
  src/main/java/com/poppy/domain/reservation/entity/Reservation.java
  src/main/java/com/poppy/domain/reservation/entity/ReservationStatus.java
  src/main/java/com/poppy/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/poppy/domain/reservation/service/AsyncRedisSlotDecrementService.java
  src/main/java/com/poppy/domain/reservation/service/RedisSlotService.java
  src/main/java/com/poppy/domain/reservation/service/ReservationService.java
  src/main/java/com/poppy/domain/review/controller/ReviewController.java
  src/main/java/com/poppy/domain/review/entity/ReviewSortType.java
  src/main/java/com/poppy/domain/review/service/ReviewService.java
  src/main/java/com/poppy/domain/user/controller/UserController.java
  src/test/java/com/poppy/domain/payment/service/PaymentServiceTest.java
  src/test/java/com/poppy/domain/reservation/service/ReservationServiceTest.java
  src/test/java/com/poppy/domain/review/service/ReviewServiceTest.java
Labels: 💯 테스트, 🔧 기능 구현

#30 [Refactor]: 결제 멱등성 보장 처리
  src/main/java/com/poppy/common/exception/ErrorCode.java
  src/main/java/com/poppy/domain/payment/service/PaymentService.java
Labels: ⚒️ 리팩토링

#32 [Build]: CI/CD 문서 수정
  .github/workflows/deploy.yml
Labels: 🏢 빌드

#33 [Build]: CI/CD 문서 수정
  .github/workflows/deploy.yml
Labels: 🏢 빌드

#34 [Feat]: 마감임박 판단 로직 구현
  src/main/java/com/poppy/domain/popupStore/controller/PopupStoreController.java
  src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java
  src/main/java/com/poppy/domain/popupStore/repository/PopupStoreRepositoryImpl.java
Labels: 🔧 기능 구현, ⚒️ 리팩토링

#35 [Feat]: 팝업 스토어 등록 시 Redis 슬롯 초기화
  src/main/java/com/poppy/admin/service/AdminService.java
  src/main/java/com/poppy/admin/service/AsyncRedisSlotInitializationService.java
  src/main/java/com/poppy/common/exception/ErrorCode.java
  src/main/java/com/poppy/common/util/RedisInitializer.java
  src/main/java/com/poppy/domain/reservation/repository/ReservationAvailableSlotCustomRepository.java
  src/main/java/com/poppy/domain/reservation/repository/ReservationAvailableSlotCustomRepositoryImpl.java
  src/main/java/com/poppy/domain/storeCategory/entity/StoreCategory.java
  src/test/java/com/poppy/admin/service/AdminServiceTest.java
Labels: 💯 테스트, 🔧 기능 구현

#37 [Feat]: 검색어 저장, 조회, 삭제 구현
  src/main/java/com/poppy/domain/popupStore/controller/PopupStoreController.java
  src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java
  src/main/java/com/poppy/domain/search/controller/SearchHistoryController.java
  src/main/java/com/poppy/domain/search/service/SearchHistoryService.java
  src/main/java/com/poppy/domain/search/service/StoreSearchService.java
  src/main/java/com/poppy/domain/user/repository/LoginUserProviderImpl.java
  src/test/java/com/poppy/domain/search/service/SearchHistoryServiceTest.java
Labels: 💯 테스트, 🔧 기능 구현

#38 [Feat]: waiting 대기열, notification 알림 구현
  .gitignore
  build.gradle
  src/main/java/com/poppy/common/config/fcm/FCMConfig.java
  src/main/java/com/poppy/common/config/redis/NotificationPublisher.java
  src/main/java/com/poppy/common/config/redis/NotificationSubscriber.java
  src/main/java/com/poppy/common/config/redis/RedisConfig.java
  src/main/java/com/poppy/common/config/security/SecurityConfig.java
  src/main/java/com/poppy/common/config/websocket/WebSocketConfig.java
  src/main/java/com/poppy/common/exception/ErrorCode.java
  src/main/java/com/poppy/domain/notification/controller/NotificationController.java
  src/main/java/com/poppy/domain/notification/dto/NotificationDto.java
  src/main/java/com/poppy/domain/notification/entity/Notification.java
  src/main/java/com/poppy/domain/notification/entity/NotificationStatus.java
  src/main/java/com/poppy/domain/notification/entity/NotificationType.java
  src/main/java/com/poppy/domain/notification/repository/NotificationRepository.java
  src/main/java/com/poppy/domain/notification/service/NotificationMessageGenerator.java
  src/main/java/com/poppy/domain/notification/service/NotificationScheduler.java
  src/main/java/com/poppy/domain/notification/service/NotificationService.java
  src/main/java/com/poppy/domain/user/controller/UserController.java
  src/main/java/com/poppy/domain/user/dto/UpdateFcmTokenReqDto.java
  src/main/java/com/poppy/domain/user/entity/User.java
  src/main/java/com/poppy/domain/user/service/UserService.java
  src/main/java/com/poppy/domain/waiting/controller/MasterWaitingController.java
  src/main/java/com/poppy/domain/waiting/controller/UserWaitingController.java
  src/main/java/com/poppy/domain/waiting/dto/request/UpdateWaitingStatusReqDto.java
  src/main/java/com/poppy/domain/waiting/dto/request/WaitingSettingsReqDto.java
  src/main/java/com/poppy/domain/waiting/dto/response/CurrentWaitingRspDto.java
  src/main/java/com/poppy/domain/waiting/dto/response/DailyWaitingRspDto.java
  src/main/java/com/poppy/domain/waiting/dto/response/UserWaitingHistoryRspDto.java
  src/main/java/com/poppy/domain/waiting/dto/response/WaitingRspDto.java
  src/main/java/com/poppy/domain/waiting/dto/response/WaitingSettingsRspDto.java
  src/main/java/com/poppy/domain/waiting/entity/Waiting.java
  src/main/java/com/poppy/domain/waiting/entity/WaitingSettings.java
  src/main/java/com/poppy/domain/waiting/entity/WaitingStatus.java
  src/main/java/com/poppy/domain/waiting/repository/WaitingRepository.java
  src/main/java/com/poppy/domain/waiting/repository/WaitingSettingsRepository.java
  src/main/java/com/poppy/domain/waiting/service/MasterWaitingService.java
  src/main/java/com/poppy/domain/waiting/service/UserWaitingService.java
  src/main/java/com/poppy/domain/waiting/service/WaitingScheduler.java
  src/main/java/com/poppy/domain/waiting/service/WaitingSettingsService.java
  src/main/java/com/poppy/domain/waiting/service/WaitingUtils.java
  src/test/java/com/poppy/domain/notification/service/NotificationServiceTest.java
  src/test/java/com/poppy/domain/user/service/UserServiceTest.java
  src/test/java/com/poppy/domain/waiting/service/MasterWaitingServiceTest.java
  src/test/java/com/poppy/domain/waiting/service/UserWaitingServiceTest.java
  src/test/java/com/poppy/domain/waiting/service/WaitingSchedulerTest.java
  src/test/java/com/poppy/domain/waiting/service/WaitingSettingsServiceTest.java
  src/test/java/com/poppy/domain/waiting/service/WaitingUtilsTest.java
Labels: 💯 테스트, 🔧 기능 구현, ⚒️ 리팩토링

#39 [Feat]: 로그인 시 닉네임 설정, 핸드폰 번호 받기 추가
  src/main/java/com/poppy/common/auth/controller/TestUserController.java
  src/main/java/com/poppy/common/auth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/poppy/domain/user/controller/UserController.java
  src/main/java/com/poppy/domain/user/dto/UpdateNicknameReqDto.java
  src/main/java/com/poppy/domain/user/entity/User.java
  src/main/java/com/poppy/domain/user/service/UserService.java
Labels: 🔧 기능 구현, ⚒️ 리팩토링

#40 [Feat]: 예약 완료 후 알림 로직 구현
  src/main/java/com/poppy/common/config/redis/NotificationPublisher.java
  src/main/java/com/poppy/common/config/redis/NotificationSubscriber.java
  src/main/java/com/poppy/common/config/security/SecurityConfig.java
  src/main/java/com/poppy/domain/notification/controller/NotificationController.java
  src/main/java/com/poppy/domain/notification/dto/NotificationDto.java
  src/main/java/com/poppy/domain/notification/dto/ReservationNotificationDto.java
  src/main/java/com/poppy/domain/notification/dto/WaitingNotificationDto.java
  src/main/java/com/poppy/domain/notification/entity/Notification.java
  src/main/java/com/poppy/domain/notification/entity/NotificationType.java
  src/main/java/com/poppy/domain/notification/service/NotificationMessageGenerator.java
  src/main/java/com/poppy/domain/notification/service/NotificationService.java
  src/main/java/com/poppy/domain/payment/dto/ReservationPaymentRspDto.java
  src/main/java/com/poppy/domain/reservation/dto/ReservationRspDto.java
  src/main/java/com/poppy/domain/reservation/entity/ReservationStatus.java
  src/main/java/com/poppy/domain/reservation/service/ReservationService.java
  src/test/java/com/poppy/domain/notification/service/NotificationServiceTest.java
  src/test/java/com/poppy/domain/reservation/service/ReservationServiceTest.java
Labels: 🔧 기능 구현

#41 [Feat]: 인기 팝업스토어 조회 로직 구현
  src/main/java/com/poppy/domain/popupStore/controller/PopupStoreController.java
  src/main/java/com/poppy/domain/popupStore/entity/PopupStore.java
  src/main/java/com/poppy/domain/popupStore/entity/PopupStoreView.java
  src/main/java/com/poppy/domain/popupStore/repository/PopupStoreRepository.java
  src/main/java/com/poppy/domain/popupStore/repository/PopupStoreViewRepository.java
  src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java
  src/test/java/com/poppy/domain/popupstore/PopupStoreServiceTest.java
Labels: 🔧 기능 구현

#42 [Fix]: 로그인 후 리다이렉트 주소 변경
  src/main/java/com/poppy/common/auth/handler/OAuth2LoginSuccessHandler.java
Labels: 🐞버그 수정

#43 [Refactor]: DTO 시간 반환 형식 변경
  src/main/java/com/poppy/common/exception/ErrorCode.java
  src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreCalenderRspDto.java
  src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java
  src/main/java/com/poppy/domain/review/dto/response/PageMetadata.java
  src/main/java/com/poppy/domain/review/dto/response/PageRspDto.java
  src/main/java/com/poppy/domain/review/dto/response/ReviewRspDto.java
  src/main/java/com/poppy/domain/user/dto/UserReservationRspDto.java
  src/main/java/com/poppy/domain/waiting/dto/request/UpdateWaitingStatusReqDto.java
  src/main/java/com/poppy/domain/waiting/dto/request/WaitingSettingsReqDto.java
Labels: ⚒️ 리팩토링

#44 [Refactor]: DTO 반환 시 description 추가
  src/main/java/com/poppy/domain/popupStore/dto/request/PopupStoreReqDto.java
  src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java
Labels: ⚒️ 리팩토링

#45 [Refactor]: 팝업 스토어 관련 링크 필드 추가
  src/main/java/com/poppy/domain/instagramReview/entity/InstagramReview.java
  src/main/java/com/poppy/domain/popupStore/dto/request/PopupStoreReqDto.java
  src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java
  src/main/java/com/poppy/domain/popupStore/entity/PopupStore.java
Labels: ⚒️ 리팩토링

#49 [Refactor]: 날짜 및 시간 형식 지정
  src/main/java/com/poppy/common/util/LocalDateWithDayOfWeekSerializer.java
  src/main/java/com/poppy/common/util/LocalTimeWithAmPmSerializer.java
  src/main/java/com/poppy/domain/payment/controller/PaymentController.java
  src/main/java/com/poppy/domain/payment/dto/ReservationPaymentRspDto.java
  src/main/java/com/poppy/domain/popupStore/dto/request/PopupStoreReqDto.java
  src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreCalenderRspDto.java
  src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java
  src/main/java/com/poppy/domain/reservation/controller/ReservationController.java
  src/main/java/com/poppy/domain/reservation/dto/request/ReservationReqDto.java
  src/main/java/com/poppy/domain/reservation/dto/response/ReservationRspDto.java
  src/main/java/com/poppy/domain/review/dto/response/ReviewRspDto.java
  src/main/java/com/poppy/domain/user/dto/response/UserReservationDetailRspDto.java
  src/main/java/com/poppy/domain/user/dto/response/UserReservationRspDto.java
  src/main/java/com/poppy/domain/waiting/dto/response/UserWaitingHistoryRspDto.java
Labels: ⚒️ 리팩토링

#51 [Feat]: 공지사항 알림 구현 및 알림 목록 전체/상세 조회 구현
  src/main/java/com/poppy/common/config/security/SecurityConfig.java
  src/main/java/com/poppy/common/exception/ErrorCode.java
  src/main/java/com/poppy/domain/notice/controller/NoticeController.java
  src/main/java/com/poppy/domain/notice/dto/NoticeDetailRspDto.java
  src/main/java/com/poppy/domain/notice/dto/NoticeReqDto.java
  src/main/java/com/poppy/domain/notice/dto/NoticeRspDto.java
  src/main/java/com/poppy/domain/notice/entity/Notice.java
  src/main/java/com/poppy/domain/notice/repository/NoticeRepository.java
  src/main/java/com/poppy/domain/notice/service/NoticeService.java
  src/main/java/com/poppy/domain/notification/controller/NotificationController.java
  src/main/java/com/poppy/domain/notification/dto/NoticeNotificationDto.java
  src/main/java/com/poppy/domain/notification/dto/NotificationDto.java
  src/main/java/com/poppy/domain/notification/dto/WaitingNotificationDto.java
  src/main/java/com/poppy/domain/notification/entity/NotificationType.java
  src/main/java/com/poppy/domain/notification/repository/NotificationRepository.java
  src/main/java/com/poppy/domain/notification/service/NotificationMessageGenerator.java
  src/main/java/com/poppy/domain/notification/service/NotificationService.java
  src/main/java/com/poppy/domain/user/repository/UserRepository.java
Labels: 🔧 기능 구현

#52 [Test]: NoticeServiceTest 구현, NotificationServiceTest 추가
  src/test/java/com/poppy/domain/notice/service/NoticeServiceTest.java
  src/test/java/com/poppy/domain/notification/service/NotificationServiceTest.java
Labels: 💯 테스트

#54 [Feat]: 스크랩 기능 구현
  src/main/java/com/poppy/common/config/security/SecurityConfig.java
  src/main/java/com/poppy/common/exception/ErrorCode.java
  src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java
  src/main/java/com/poppy/domain/popupStore/entity/PopupStore.java
  src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java
  src/main/java/com/poppy/domain/scrap/controller/ScrapController.java
  src/main/java/com/poppy/domain/scrap/dto/ScrapRspDto.java
  src/main/java/com/poppy/domain/scrap/dto/UserScrapRspDto.java
  src/main/java/com/poppy/domain/scrap/entity/Scrap.java
  src/main/java/com/poppy/domain/scrap/entity/ScrapSortType.java
  src/main/java/com/poppy/domain/scrap/repository/ScrapRepository.java
  src/main/java/com/poppy/domain/scrap/service/ScrapService.java
  src/main/java/com/poppy/domain/user/entity/User.java
Labels: 🔧 기능 구현

#55 [Feat]: 스케줄러 알림 로직 분산 락 적용
  src/main/java/com/poppy/domain/waiting/service/DistributedLockService.java
  src/main/java/com/poppy/domain/waiting/service/WaitingScheduler.java
  src/test/java/com/poppy/domain/waiting/service/WaitingSchedulerTest.java
Labels: 💯 테스트, 🔧 기능 구현

#56 [Refactor]: ReviewLike 분산락 적용
  src/main/java/com/poppy/common/exception/ErrorCode.java
  src/main/java/com/poppy/domain/review/service/ReviewService.java
Labels: ⚒️ 리팩토링

#57 [Refactor]: 팝업스토어 검색 필터링 구현
  src/main/java/com/poppy/domain/popupStore/controller/PopupStoreController.java
  src/main/java/com/poppy/domain/popupStore/dto/request/PopupStoreSearchReqDto.java
  src/main/java/com/poppy/domain/popupStore/repository/PopupStoreRepositoryCustom.java
  src/main/java/com/poppy/domain/popupStore/repository/PopupStoreRepositoryImpl.java
  src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java
  src/test/java/com/poppy/domain/popupstore/PopupStoreServiceTest.java
Labels: 🔧 기능 구현, ⚒️ 리팩토링

#58 [Feat]: Notification 스케줄러 분산 락 적용
  src/main/java/com/poppy/common/config/redis/DistributedLockService.java
  src/main/java/com/poppy/domain/notification/service/NotificationCleanupScheduler.java
  src/main/java/com/poppy/domain/waiting/service/WaitingTimeoutScheduler.java
  src/test/java/com/poppy/domain/notification/service/NotificationCleanupSchedulerTest.java
  src/test/java/com/poppy/domain/waiting/service/WaitingTimeoutSchedulerTest.java
Labels: 💯 테스트, 🔧 기능 구현, ⚒️ 리팩토링

#60 [Feat]: 로깅 처리 구현
  build.gradle
  src/main/java/com/poppy/common/aop/LoggingAspect.java
  src/main/resources/logback-spring.xml
Labels: 📃 문서, 🔧 기능 구현

#61 [refactor]: PopupStoreRspDto 날짜 및 시간 형식 수정
  src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java
Labels: ⚒️ 리팩토링

#62 [Feat]: Waiting 날짜와 시간대별 목록 조회 추가, 대기 등록 시 유효성 검사 추가
  src/main/java/com/poppy/common/exception/ErrorCode.java
  src/main/java/com/poppy/domain/notice/repository/NoticeRepository.java
  src/main/java/com/poppy/domain/waiting/controller/MasterWaitingController.java
  src/main/java/com/poppy/domain/waiting/dto/response/DailyWaitingRspDto.java
  src/main/java/com/poppy/domain/waiting/dto/response/UserWaitingHistoryRspDto.java
  src/main/java/com/poppy/domain/waiting/entity/Waiting.java
  src/main/java/com/poppy/domain/waiting/repository/WaitingRepository.java
  src/main/java/com/poppy/domain/waiting/service/MasterWaitingService.java
  src/main/java/com/poppy/domain/waiting/service/UserWaitingService.java
  src/test/java/com/poppy/domain/waiting/service/UserWaitingServiceTest.java
Labels: 🔧 기능 구현, ⚒️ 리팩토링

#63 [Refactor]: Redis connection pool 및 container 설정
  build.gradle
  src/main/java/com/poppy/common/config/redis/RedisConfig.java
Labels: 📃 문서, ⚒️ 리팩토링

#65 [Feat]: 리뷰, 팝업 스토어 관련 이미지 S3 처리
  .gitignore
  build.gradle
  src/main/java/com/poppy/admin/controller/AdminController.java
  src/main/java/com/poppy/admin/service/AdminService.java
  src/main/java/com/poppy/common/config/multipart/MultipartConfig.java
  src/main/java/com/poppy/common/config/s3/S3Config.java
  src/main/java/com/poppy/common/entity/Images.java
  src/main/java/com/poppy/common/exception/ErrorCode.java
  src/main/java/com/poppy/common/repository/ImageRepository.java
  src/main/java/com/poppy/common/service/ImageService.java
  src/main/java/com/poppy/domain/popupStore/dto/request/PopupStoreReqDto.java
  src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java
  src/main/java/com/poppy/domain/popupStore/entity/PopupStore.java
  src/main/java/com/poppy/domain/popupStore/entity/PopupStoreView.java
  src/main/java/com/poppy/domain/review/controller/ReviewController.java
  src/main/java/com/poppy/domain/review/dto/request/ReviewReqDto.java
  src/main/java/com/poppy/domain/review/dto/response/ReviewRspDto.java
  src/main/java/com/poppy/domain/review/entity/Review.java
  src/main/java/com/poppy/domain/review/service/ReviewService.java
  src/main/java/com/poppy/domain/scrap/dto/UserScrapRspDto.java
  src/main/java/com/poppy/domain/user/dto/response/UserReservationRspDto.java
Labels: 🔧 기능 구현

#67 [Fix]: 테스트 유저 생성 로직 변경
  src/main/java/com/poppy/common/auth/controller/TestUserController.java
Labels: 🐞버그 수정

#66 [Test]: MasterWaitingServiceTest, UserWaitingServiceTest 메소드 추가
  src/test/java/com/poppy/domain/waiting/service/MasterWaitingServiceTest.java
  src/test/java/com/poppy/domain/waiting/service/UserWaitingServiceTest.java
Labels: 💯 테스트

#68 [Feat]: 특정 구 내에 있는 팝업스토어 검색
  build.gradle
  src/main/java/com/poppy/domain/popupStore/controller/PopupStoreController.java
  src/main/java/com/poppy/domain/popupStore/repository/PopupStoreRepository.java
  src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java
Labels: 🔧 기능 구현

#69 [Fix]: 웨이팅 알림 등록 날짜/시간 추가, 공지사항 조회 시 id 필드 추가
  src/main/java/com/poppy/domain/notice/dto/NoticeRspDto.java
  src/main/java/com/poppy/domain/waiting/dto/response/WaitingRspDto.java
  src/main/java/com/poppy/domain/waiting/entity/Waiting.java
Labels: ⚒️ 리팩토링

#70 [Test]: 이미지 관련 테스트 코드 수정
  src/test/java/com/poppy/admin/service/AdminServiceTest.java
  src/test/java/com/poppy/domain/popupstore/PopupStoreServiceTest.java
  src/test/java/com/poppy/domain/review/service/ReviewServiceTest.java
Labels: 💯 테스트

#71 [Feat]: 리뷰 변동시 연관된 팝업스토어의 평점 갱신
  src/main/java/com/poppy/domain/popupStore/entity/PopupStore.java
  src/main/java/com/poppy/domain/review/repository/ReviewRepository.java
  src/main/java/com/poppy/domain/review/service/ReviewService.java
Labels: 🔧 기능 구현

#72 [Refactor]: 예약 취소 알림 구현
  src/main/java/com/poppy/common/service/ImageService.java
  src/main/java/com/poppy/domain/notification/dto/ReservationNotificationDto.java
  src/main/java/com/poppy/domain/notification/dto/WaitingNotificationDto.java
  src/main/java/com/poppy/domain/notification/entity/NotificationType.java
  src/main/java/com/poppy/domain/notification/service/NotificationMessageGenerator.java
  src/main/java/com/poppy/domain/notification/service/NotificationService.java
  src/main/java/com/poppy/domain/payment/repository/PaymentRepository.java
  src/main/java/com/poppy/domain/reservation/entity/Reservation.java
  src/main/java/com/poppy/domain/reservation/service/ReservationService.java
  src/main/java/com/poppy/domain/user/dto/response/UserReservationDetailRspDto.java
  src/main/java/com/poppy/domain/user/dto/response/UserReservationRspDto.java
  src/test/java/com/poppy/domain/notification/service/NotificationServiceTest.java
Labels: 🔧 기능 구현, ⚒️ 리팩토링

#73 [Refactor]: 로그인 시 유저 닉네임 반환
  src/main/java/com/poppy/common/auth/JwtTokenizer.java
  src/main/java/com/poppy/common/auth/dto/TokenRspDto.java
Labels: ⚒️ 리팩토링

#74 [Fix]: CORS 설정 수정
  src/main/java/com/poppy/common/auth/cache/OAuthOTUCache.java
  src/main/java/com/poppy/common/config/security/SecurityConfig.java
Labels: 🐞버그 수정

#75 [Refactor]: 팝업 스토어 반환 시 조회 수 추가
  src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java
Labels: ⚒️ 리팩토링

#76 [Feat]: 유저 예약 24시간 전 알림 구현
  src/main/java/com/poppy/common/auth/JwtTokenizer.java
  src/main/java/com/poppy/common/config/redis/DistributedLockService.java
  src/main/java/com/poppy/common/config/redis/NotificationPublisher.java
  src/main/java/com/poppy/common/config/redis/NotificationSubscriber.java
  src/main/java/com/poppy/common/config/websocket/WebSocketConfig.java
  src/main/java/com/poppy/domain/notification/dto/WaitingNotificationDto.java
  src/main/java/com/poppy/domain/notification/entity/Notification.java
  src/main/java/com/poppy/domain/notification/entity/NotificationType.java
  src/main/java/com/poppy/domain/notification/service/NotificationMessageGenerator.java
  src/main/java/com/poppy/domain/notification/service/NotificationService.java
  src/main/java/com/poppy/domain/reservation/dto/response/ReservationRspDto.java
  src/main/java/com/poppy/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/poppy/domain/reservation/service/ReservationReminderScheduler.java
Labels: 🔧 기능 구현, ⚒️ 리팩토링
