Repository Pop-py/poppy-server, pull requests merged in 2025-01, with the labels that each got.

#78 [Feat]: 회원 탈퇴 구현
  src/main/java/com/poppy/common/exception/ErrorCode.java
  src/main/java/com/poppy/domain/user/controller/UserController.java
  src/main/java/com/poppy/domain/user/entity/User.java
  src/main/java/com/poppy/domain/user/service/UserService.java
Labels: 🔧 기능 구현

#79 [Fix]: 팝업 스토어 등록 로직 에러 해결
  src/main/java/com/poppy/admin/service/AsyncRedisSlotInitializationService.java
  src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java
Labels: 🐞버그 수정

#80 [Feat]: 인기 검색어 조회 구현
  src/main/java/com/poppy/PoppyApplication.java
  src/main/java/com/poppy/common/config/security/SecurityConfig.java
  src/main/java/com/poppy/domain/search/controller/SearchHistoryController.java
  src/main/java/com/poppy/domain/search/service/HourlyKeywordScheduler.java
  src/main/java/com/poppy/domain/search/service/PopularKeywordService.java
  src/main/java/com/poppy/domain/search/service/StoreSearchService.java
Labels: 🔧 기능 구현

#81 [Feat]: 저장해놓은 팝업스토어 오픈일이 되면 알림 전송 구현
  src/main/java/com/poppy/common/config/redis/DistributedLockService.java
  src/main/java/com/poppy/domain/notification/dto/ScrapedStoreNotificationDto.java
  src/main/java/com/poppy/domain/notification/entity/NotificationType.java
  src/main/java/com/poppy/domain/notification/service/NotificationMessageGenerator.java
  src/main/java/com/poppy/domain/notification/service/NotificationService.java
  src/main/java/com/poppy/domain/scrap/repository/ScrapRepository.java
  src/main/java/com/poppy/domain/scrap/service/ScrapOpeningNotificationScheduler.java
Labels: 🔧 기능 구현

#82 [Feat]: 팝업스토어 수정
  src/main/java/com/poppy/common/exception/ErrorCode.java
  src/main/java/com/poppy/domain/popupStore/controller/PopupStoreController.java
  src/main/java/com/poppy/domain/popupStore/dto/request/PopupStoreUpdateReqDto.java
  src/main/java/com/poppy/domain/popupStore/entity/PopupStore.java
  src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java
  src/main/java/com/poppy/domain/reservation/repository/ReservationAvailableSlotRepository.java
  src/main/java/com/poppy/domain/reservation/repository/ReservationRepository.java
Labels: 🔧 기능 구현

#83 [Feat]: 유저별 최근 본 팝업 스토어 조회
  src/main/java/com/poppy/common/config/security/SecurityConfig.java
  src/main/java/com/poppy/domain/popupStore/entity/PopupStoreView.java
  src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java
  src/main/java/com/poppy/domain/user/controller/UserController.java
  src/main/java/com/poppy/domain/user/dto/response/UserPopupStoreRspDto.java
  src/main/java/com/poppy/domain/user/repository/LoginUserProvider.java
  src/main/java/com/poppy/domain/user/repository/LoginUserProviderImpl.java
  src/main/java/com/poppy/domain/user/repository/UserRepository.java
  src/main/java/com/poppy/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/poppy/domain/user/repository/UserRepositoryCustomImpl.java
  src/main/java/com/poppy/domain/user/service/UserService.java
Labels: 🔧 기능 구현

#84 [Fix]: fcm 알림 전송 로직 별도 트랜잭션으로 분리
  src/main/java/com/poppy/domain/notification/service/NotificationService.java
  src/main/java/com/poppy/domain/waiting/service/MasterWaitingService.java
Labels: 🐞버그 수정

#85 [Fix]: 로그인한 유저만 최근 본 팝업 스토어 조회하도록 변경
  src/main/java/com/poppy/common/config/security/SecurityConfig.java
  src/main/java/com/poppy/domain/user/service/UserService.java
Labels: 🐞버그 수정

#86 [Refactor]: 로그인 유저 반환 시 핸드폰 번호도 반환하도록 변경
  src/main/java/com/poppy/common/auth/JwtTokenizer.java
  src/main/java/com/poppy/common/auth/dto/TokenRspDto.java
Labels: ⚒️ 리팩토링

#88 [Refactor]: 예약 완료 시 reservationId 반환 추가
  src/main/java/com/poppy/domain/reservation/dto/response/ReservationRspDto.java
Labels: ⚒️ 리팩토링

#89 [Refactor]: 예약 내역 조회 url 변경
  src/main/java/com/poppy/domain/user/controller/UserController.java
Labels: ⚒️ 리팩토링

#90 [fix]: ScrapCount 반환 오류 수정
  src/main/java/com/poppy/domain/scrap/service/ScrapService.java
Labels: 🐞버그 수정

#92 [Fix]: 스크랩 토글 안 되던 문제 해결
  src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java
  src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java
  src/main/java/com/poppy/domain/review/controller/ReviewController.java
  src/main/java/com/poppy/domain/review/dto/response/ReviewRspDto.java
  src/main/java/com/poppy/domain/review/service/ReviewService.java
  src/main/java/com/poppy/domain/scrap/controller/ScrapController.java
  src/main/java/com/poppy/domain/scrap/repository/ScrapRepository.java
  src/main/java/com/poppy/domain/scrap/service/ScrapService.java
Labels: 🐞버그 수정, ⚒️ 리팩토링

#93 [Feat]: 비슷한 팝업 추천 로직 구현
  src/main/java/com/poppy/domain/popupStore/controller/PopupStoreController.java
  src/main/java/com/poppy/domain/popupStore/repository/PopupStoreRepositoryCustom.java
  src/main/java/com/poppy/domain/popupStore/repository/PopupStoreRepositoryImpl.java
  src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java
Labels: 🔧 기능 구현

#94 [Fix]: 리뷰 개수 조회 문제 해결
  src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java
Labels: 🐞버그 수정

#95 [Feat]: 마감이 임박한 팝업스토어 list 반환
  src/main/java/com/poppy/domain/popupStore/controller/PopupStoreController.java
  src/main/java/com/poppy/domain/popupStore/repository/PopupStoreRepository.java
  src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java
Labels: 🔧 기능 구현

#96 [Fix]: 팝업 스토어 운영 시간 확인 로직 변경
  src/main/java/com/poppy/domain/waiting/service/UserWaitingService.java
Labels: 🐞버그 수정

#97 [Chore]: 현재 시간 확인 로그 추가
  src/main/java/com/poppy/domain/waiting/controller/UserWaitingController.java
  src/main/java/com/poppy/domain/waiting/service/UserWaitingService.java
  src/test/java/com/poppy/domain/waiting/service/UserWaitingServiceTest.java
Labels: 🎸 기타

#98 [fix]: reservation 반환시 reservationId 함께 반환하도록 수정
  src/main/java/com/poppy/domain/user/dto/response/UserReservationRspDto.java
Labels: ⚒️ 리팩토링

#99 [Fix]: UserWaitingHistoryRspDto 썸네일 추가
  src/main/java/com/poppy/domain/waiting/dto/response/UserWaitingHistoryRspDto.java
Labels: 🐞버그 수정

#100 [Fix]: dto 필드 수정
  src/main/java/com/poppy/domain/user/dto/response/UserReservationRspDto.java
  src/main/java/com/poppy/domain/waiting/dto/response/UserWaitingHistoryRspDto.java
Labels: 🐞버그 수정

#101 [Fix]: dto 필드 추가
  src/main/java/com/poppy/domain/waiting/dto/response/UserWaitingHistoryRspDto.java
Labels: 🐞버그 수정

#102 [Refactor]: 로그인/회원가입 시 userId 반환
  src/main/java/com/poppy/common/auth/JwtTokenizer.java
  src/main/java/com/poppy/common/auth/dto/TokenRspDto.java
Labels: ⚒️ 리팩토링

#103 [Refactor]: 유저 스크랩 조회 반환 변경
  src/main/java/com/poppy/domain/scrap/controller/ScrapController.java
  src/main/java/com/poppy/domain/scrap/dto/UserScrapRspDto.java
  src/main/java/com/poppy/domain/scrap/service/ScrapService.java
Labels: 🔧 기능 구현, ⚒️ 리팩토링

#104 [Feat]: 유저별 리뷰 조회 로직 구현
  src/main/java/com/poppy/domain/review/repository/ReviewRepository.java
  src/main/java/com/poppy/domain/review/service/ReviewService.java
  src/main/java/com/poppy/domain/user/controller/UserController.java
  src/main/java/com/poppy/domain/user/dto/response/UserReviewRspDto.java
Labels: 🔧 기능 구현

#105 [Refactor]: 스크랩 삭제 여러 개 가능하도록 수정
  src/main/java/com/poppy/domain/scrap/controller/ScrapController.java
  src/main/java/com/poppy/domain/scrap/dto/request/UserScrapReqDto.java
  src/main/java/com/poppy/domain/scrap/dto/response/ScrapRspDto.java
  src/main/java/com/poppy/domain/scrap/dto/response/UserScrapRspDto.java
  src/main/java/com/poppy/domain/scrap/repository/ScrapRepository.java
  src/main/java/com/poppy/domain/scrap/service/ScrapService.java
Labels: ⚒️ 리팩토링

#106 [Fix]: websocket 메시지 형식 수정 및 dto 필드(날짜, 시간) 추가
  src/main/java/com/poppy/domain/notification/dto/NoticeNotificationDto.java
  src/main/java/com/poppy/domain/notification/dto/ReservationNotificationDto.java
  src/main/java/com/poppy/domain/notification/service/NotificationMessageGenerator.java
  src/main/java/com/poppy/domain/notification/service/NotificationService.java
  src/test/java/com/poppy/domain/notification/service/NotificationServiceTest.java
Labels: 🐞버그 수정
