Repository Pop-py/poppy-server, pull requests merged in 2025-02, with the labels that each got.

#107 [Feat]: 리뷰 상세 조회 구현
  src/main/java/com/poppy/domain/review/controller/ReviewController.java
  src/main/java/com/poppy/domain/review/service/ReviewService.java
Labels: 🔧 기능 구현

#108 [Fix]: WaitingNotificationDto 필드(날짜, 시간) 추가
  src/main/java/com/poppy/domain/notification/dto/WaitingNotificationDto.java
Labels: 🐞버그 수정

#110 [Fix]: 리뷰 수정 시 기존 이미지 삭제되는 문제 해결
  src/main/java/com/poppy/domain/review/dto/request/ReviewReqDto.java
  src/main/java/com/poppy/domain/review/dto/response/ReviewRspDto.java
  src/main/java/com/poppy/domain/review/entity/Review.java
  src/main/java/com/poppy/domain/review/service/ReviewService.java
Labels: 🐞버그 수정

#111 [fix]: review 반환시 이미지 업로드 Url, location 추가
  src/main/java/com/poppy/domain/user/dto/response/UserReviewRspDto.java
Labels: ⚒️ 리팩토링

#112 [Chore]: thumbnail 필드명 변경
  src/main/java/com/poppy/domain/scrap/dto/response/UserScrapRspDto.java
Labels: 🎸 기타

#113 [Chore]: popupStoreId 필드명 변경
  src/main/java/com/poppy/domain/scrap/dto/response/UserScrapRspDto.java
Labels: 🎸 기타

#114 [Fix]: WebSocket 경로 변경
  src/main/java/com/poppy/common/config/redis/NotificationSubscriber.java
  src/main/java/com/poppy/common/config/websocket/WebSocketConfig.java
Labels: 🐞버그 수정

#115 [Fix]: WebSocketConfig 수정
  src/main/java/com/poppy/common/config/websocket/WebSocketConfig.java
Labels: 🐞버그 수정

#116 [Feat]: 공지사항 WebSocket 알림 경로 추가
  src/main/java/com/poppy/common/config/redis/NotificationSubscriber.java
Labels: 🔧 기능 구현

#117 [Feat]: Health Check API 추가
  src/main/java/com/poppy/common/api/HealthCheckController.java
Labels: 🔧 기능 구현

#118 [Fix]: Health Check 반환 변경
  src/main/java/com/poppy/common/api/HealthCheckController.java
Labels: 🐞버그 수정

#119 [Fix]: blue/green 배포 반영
  .github/workflows/deploy.yml
Labels: 🐞버그 수정
